server:
  port: 8081
spring:
  application:
    name: database
  datasource:
    url: jdbc:mysql://localhost:3306/basedata
    username: root
    password: 123
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB